import { NextRequest, NextResponse } from "next/server";

export const runtime = "nodejs";

export async function POST(request: NextRequest) {
  let body: any;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ ok: false, message: "Invalid request body." }, { status: 400 });
  }

  const { prompt } = body;
  if (!prompt || typeof prompt !== 'string') {
    return NextResponse.json({ ok: false, message: "Prompt is required." }, { status: 422 });
  }

  // --- VERY SIMPLE HEURISTIC PARSER FOR DEMO PURPOSES ---
  // In a real production app, you would pass the `prompt` to OpenAI/Gemini API here.
  
  const lowerPrompt = prompt.toLowerCase();
  
  // Extract URL if present
  const urlMatch = prompt.match(/(https?:\/\/[^\s]+|[\w-]+\.[\w.-]+\.[a-zA-Z]{2,})/);
  let targetUrl = urlMatch ? urlMatch[0] : '/app-url';
  targetUrl = targetUrl.replace(/['",.;)]+$/, '');
  const displayUrl = targetUrl.startsWith('http') ? targetUrl : `https://${targetUrl}`;

  // Determine context
  let contextName = "Custom User Workflow";
  if (lowerPrompt.includes("login") || lowerPrompt.includes("password") || lowerPrompt.includes("user name")) {
    contextName = "User Authentication Flow";
  } else if (lowerPrompt.includes("cart") || lowerPrompt.includes("checkout") || lowerPrompt.includes("price") || lowerPrompt.includes("promo")) {
    contextName = "E-Commerce Transaction Flow";
  } else if (lowerPrompt.includes("book") || lowerPrompt.includes("flight") || lowerPrompt.includes("hotel")) {
    contextName = "Travel Booking Flow";
  }

  // Parse steps for BDD
  // Split prompt by commas, "and", "then" to create semi-realistic BDD steps
  const rawSteps = prompt
    .replace(/Navigate to ['"][^'"]+['"]/gi, '')
    .replace(/Navigate ['"][^'"]+['"]/gi, '')
    .split(/,| and | then /i)
    .map(s => s.trim())
    .filter(s => s.length > 3);

  let bddSteps = rawSteps.map((step, idx) => {
    // Capitalize first letter
    const formattedStep = step.charAt(0).toLowerCase() + step.slice(1);
    if (idx === 0) return `    When the user ${formattedStep}`;
    if (idx === rawSteps.length - 1 && formattedStep.includes('verify')) return `    Then ${formattedStep}`;
    return `    And the user ${formattedStep}`;
  }).join('\n');

  if (!bddSteps) {
    bddSteps = `    When the user executes the requested actions\n    Then the system should respond correctly`;
  }

  // Generate BDD
  const bddScenario = `Feature: ${contextName}

  Scenario: Execute requested workflow successfully
    Given the user navigates to ${displayUrl}
${bddSteps}
    And the final state should be verified against expectations`;

  // Generate Playwright
  let pwScript = `import { test, expect } from '@playwright/test';
import { QAQuadAI } from '@qaquad/ai-engine';

test('${contextName}', async ({ page }) => {
  await page.goto('${displayUrl}');
  
  // AI autonomously interprets the prompt and executes actions
  await QAQuadAI.executePrompt(page, \`
    ${prompt}
  \`);
  
  // Implicit assertions generated by AI
  await expect(page).not.toHaveURL(/.*error.*/);
  const errors = await page.locator('.error-message').count();
  expect(errors).toBe(0);
});`;

  // Generate Edge Cases dynamically based on keywords
  const edgeCases = [
    "Simulate extreme network latency during execution",
  ];
  
  if (lowerPrompt.includes("promo") || lowerPrompt.includes("discount")) {
    edgeCases.push("Applying expired or invalid promo code");
    edgeCases.push("Applying promo code twice consecutively");
  } else if (lowerPrompt.includes("password")) {
    edgeCases.push("Submitting empty username/password fields");
    edgeCases.push("Attempting login with incorrect password 5 times (Rate limit check)");
  } else if (lowerPrompt.includes("cart") || lowerPrompt.includes("add")) {
    edgeCases.push("Adding item to cart then immediately refreshing page");
    edgeCases.push("Adding maximum allowed quantity of items to cart");
  } else {
    edgeCases.push("Rapid consecutive clicks on action buttons");
    edgeCases.push("Unexpected popups or modals interrupting the flow");
  }

  // Generate Security Cases dynamically
  const securityCases = [
    "XSS payload injection in available text fields",
  ];

  if (lowerPrompt.includes("price") || lowerPrompt.includes("cart")) {
    securityCases.push("Attempting to manipulate price payload via API interception");
    securityCases.push("Bypassing client-side inventory validation");
  } else if (lowerPrompt.includes("login") || lowerPrompt.includes("admin")) {
    securityCases.push("SQL Injection attempt in authentication fields (' OR 1=1 --)");
    securityCases.push("Session hijacking and token reuse simulation");
  } else {
    securityCases.push("Bypassing client-side validation logic");
    securityCases.push("Forced browsing to unauthorized endpoints");
  }

  return NextResponse.json({ 
    ok: true, 
    bdd: bddScenario,
    playwright: pwScript,
    edgeCases,
    securityCases
  });
}
